<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="wwwroot\Uploads\NovaPasta1\**" />
    <Compile Remove="wwwroot\Uploads\NovaPasta\**" />
    <Content Remove="wwwroot\Uploads\NovaPasta1\**" />
    <Content Remove="wwwroot\Uploads\NovaPasta\**" />
    <EmbeddedResource Remove="wwwroot\Uploads\NovaPasta1\**" />
    <EmbeddedResource Remove="wwwroot\Uploads\NovaPasta\**" />
    <None Remove="wwwroot\Uploads\NovaPasta1\**" />
    <None Remove="wwwroot\Uploads\NovaPasta\**" />
  </ItemGroup>

  <ItemGroup>
    <Content Remove="wwwroot\Uploads\cnpj\5086480d-38a8-404e-87a3-ff8b41182faa.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\522f95d3-23ba-4bf8-8923-e37c5e2fb9af.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\6b2de1d6-3786-4001-a9b3-b558b360b892.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\838e780f-9fdb-418a-b878-2625a4b13b6d.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\a5de3d01-5de1-4a39-a7ad-7f800440d2f7.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\e9dc701a-ab05-421f-abb8-a149f8544bc3.pdf" />
    <Content Remove="wwwroot\Uploads\cnpj\fcf0aac2-c1e7-4edd-9d1e-b2aab534d963.pdf" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.24" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.24">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.6.2" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\Uploads\cnpj\" />
    <Folder Include="wwwroot\Uploads\certificado\" />
  </ItemGroup>

</Project>
